  WORKSPACENAME: mlw-exp
  RESOURCEGROUPNAME: ml-exp-rg
  KEYVAULTNAME: mlwexp6167533864
  MODELNAME: mini-batch-k-means-customer-segmentation
  DESCRIPTION: 'Given a set of customer features, this model will output the customer profile.'
  CONDAENVNAME: azureml_py38_dev