$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: py38-segmentation-dev
description: 'An environment to work with transformers in a dev box'
version: 5
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
os_type: linux
tags:
  framework: sklearn
conda_file: conda_dependencies.yml