name: model-cd

on:
  workflow_dispatch:
  push:
    # branches: [ main ]
    paths:
    - .aml/jobs/**
    - src/**
    - .github/workflows/**

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
            files: .github/variables.yaml

      - id: job_preparation
        name: Installing dependencies
        uses: ./.github/actions/aml-cli-install
        with:
          componentSupport: false
          minVersion: 2.0

      - name: Logging into Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Ensuring environment
        uses: ./.github/actions/aml-env-ensure
        with:
          envFile: .aml/environments/${CONDAENVNAME}/environment.yml
          validateOnly: true
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
      
      - name: Running training job
        id: jobRun
        uses: ./.github/actions/aml-job-create
        with:
          name: ${{ env.MODELNAME }}
          jobFile: .aml/jobs/customer-segmentation/train.job.yml
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
          noWait: false
      
    outputs:
      jobName: ${{ steps.jobRun.outputs.jobName }}

  register-model:
    environment: dev
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
            files: .github/variables.yaml

      - id: job_preparation
        name: Installing dependencies
        uses: ./.github/actions/aml-cli-install
        with:
          componentSupport: false
          minVersion: 2.0
          pythonTools: true

      - name: Logging into Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Registering trained model
        uses: ./.github/actions/aml-model-register
        with:
          name: ${MODELNAME}
          fromJob: true
          jobName: ${{ needs.build.outputs.jobName }}
          description: ${DESCRIPTION}
          modelPath: model
          modelType: mlflow_model
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}

  deploy:
    environment: dev
    runs-on: ubuntu-latest
    needs: register-model

    steps:
      - uses: actions/checkout@v2

      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
            files: .github/variables.yaml

      - id: job_preparation
        name: Installing dependencies
        uses: ./.github/actions/aml-cli-install
        with:
          componentSupport: false
          minVersion: 2.0
          pythonTools: true

      - name: Logging into Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Moving model's stage
        uses: ./.github/actions/aml-model-set
        with:
          modelName: ${MODELNAME}
          modelVersion: latest
          property: purpose
          value: tutorial
          isMlflowStage: true
          replaceExistingWith: archived
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
      
      - name: Deploying models
        id: deployment
        uses: ./.github/actions/aml-endpoint-deploy
        with:
          endpointFile: .aml/endpoints/*/endpoint.yml
          deploymentFile: deployments/*.yml
          modelVersion: latest
          workspaceName: ${WORKSPACENAME}
          resourceGroup: ${RESOURCEGROUPNAME}
          secretsToKeyVault: true
          keyVaultName: ${KEYVAULTNAME}